//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Req
    {
        public int id { get; set; }
        public int clientID { get; set; }
        public int veloID { get; set; }
        public System.DateTime dateT { get; set; }
        public System.DateTime dateNT { get; set; }
        public Nullable<System.DateTime> dateRR { get; set; }
        public Nullable<int> pointID { get; set; }
        public Nullable<int> returnPointID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual RentPoints RentPoints { get; set; }
        public virtual Velos Velos { get; set; }
        public virtual RentPoints RentPoints1 { get; set; }
    }
}
